### ISSUE TITLE
Time-based EvaluationRule support

### ISSUE THREAD

**Issue by Logianer** [Schrankian/campus-dual-app#19]
It would be helpful to create an Evaluation Rule that matches based on the Lesson start and end time.

Example:
```
Rule:
Time: "12.00"
Color: #ff0000
```
would color every lesson that contains the minute "12.00":
9.00 - 10.00 - no match
10.15 - 11.15 - no match
11.30 - 12.30 - match!
etc.

If a lesson ends or starts with the given time, it will also match.

**Comment by Schrankian** [comment]
Sure that looks like a good idea. What would the use case be? And is one timestamp enough or would it be better to define a timespan, like 12:00-14:00 to which the Rule applies?
